// 应用偏好 i18n 字典与 t()。主题/语言状态由 useSettings 管理（持久化到后端）。
// 项目未安装 vue-i18n，故用模块级手写字典实现轻量 i18n；t() 读取 useSettings
// 的响应式 locale，语言切换时所有模板中调用 t() 的组件自动重渲染。

import type { Locale } from './useSettings';
import { settings } from './useSettings';

/** 中英文案字典 */
const messages: Record<Locale, Record<string, string>> = {
  zh: {
    'common.save': '保存',
    'common.delete': '删除',
    'common.rename': '重命名',
    'common.cancel': '取消',
    'common.close': '关闭',
    'common.local': '本地',
    'common.remote': '远端',
    'common.dynamic': '动态',
    'common.note': '备注',
    'common.actions': '操作',
    'common.enable': '启用',
    'common.listenAddr': '监听地址',
    'common.targetAddr': '目标地址',
    'common.remoteAddr': '远端地址',
    'common.localAddr': '本地地址',
    'common.unnamed': '未命名主机',
    'common.unknown': '未知',

    'hostbar.title': '已保存主机',
    'hostbar.namePlaceholder': '主机名称',
    'hostbar.addHost': '添加主机',

    'lang.title': '语言',
    'lang.zh': '简体中文',
    'lang.en': 'English',

    'theme.title': '主题',
    'theme.dark': '深色',
    'theme.light': '浅色',

    'conn.title': 'SSH 连接信息',
    'conn.subtitle': '填写远端主机凭据以建立隧道',
    'conn.host': '主机 Host',
    'conn.port': '端口 Port',
    'conn.username': '用户名',
    'conn.password': '密码',
    'conn.keyPath': '私钥路径',
    'conn.keyPathPlaceholder': '可选，留空使用密码认证',
    'conn.browse': '浏览',
    'conn.start': '启动',
    'conn.stop': '关闭',
    'conn.connecting': '连接中…',
    'conn.show': '显示',
    'conn.hide': '隐藏',

    'pf.title': '端口转发规则',
    'pf.add': '添加规则',

    'rt.targetRemote': '远端地址 → 本地地址',
    'rt.arrow': '远端 → 本地',
    'rt.upload': '上传',
    'rt.download': '下载',
    'rt.empty.local': '暂无本地转发规则',
    'rt.empty.remote': '暂无远端转发规则',
    'rt.empty.dynamic': '暂无动态转发规则',
    'rt.edit': '修改',
    'rt.delete': '删除',

    'rm.title': '修改转发规则',
    'rm.type': '转发类型',
    'rm.notePlaceholder': '可选备注',

    'log.title': '运行日志',
    'log.count': '{n} 条',
    'log.copy': '复制全部',
    'log.copied': '已复制',
    'log.clear': '清空',
    'log.empty': '暂无日志',

    'status.idle': '未连接',
    'status.connecting': '连接中',
    'status.connected': '已连接',
    'status.error': '连接失败',
    'status.disconnecting': '断开中',

    'logmsg.switchHost': '已切换主机：{name}（{host}）',
    'logmsg.saveHost': '已保存主机「{name}」配置',
    'logmsg.deleteHost': '已删除主机「{name}」',
    'logmsg.addRule': '已新增规则 {desc}',
    'logmsg.draft': '草稿',
    'logmsg.removeRule': '已删除规则 {desc}',
    'logmsg.toggleRule': '规则 {desc}',
    'logmsg.enabled': '已启用',
    'logmsg.disabled': '已停用',
    'logmsg.updateRule': '规则已更新 {desc}（{field}）',
    'logmsg.modifyRule': '规则已修改 {desc}',
    'logmsg.noHost': '未选择主机',
    'logmsg.hostRequired': '主机地址不能为空',
    'logmsg.portInvalid': '端口需为 1-65535',
    'logmsg.usernameRequired': '用户名不能为空',
    'logmsg.validateFail': '表单校验失败，请检查必填项',
    'logmsg.connecting': '正在连接 {host}:{port}（用户 {username}）…',
    'logmsg.connected': '已连接到 {host}:{port}',
    'logmsg.noEnabledRule': '当前没有启用的转发规则',
    'logmsg.established': '已建立转发 {desc}',
    'logmsg.closing': '正在关闭所有转发通道…',
    'logmsg.disconnected': '已断开与 {host} 的连接',
    'logmsg.pickKey': '已选择私钥：{path}',
    'logmsg.loading': '载入主机配置…',
    'logmsg.loaded': '已载入 {n} 个主机配置',
    'logmsg.waiting': '等待连接…',
    'logmsg.createdDefaultHost': '已自动创建默认主机「{name}」',
    'logmsg.addHost': '已添加主机「{name}」',
    'logmsg.saveHostFirst': '请先保存主机配置',
    'logmsg.discardHost': '已丢弃未保存的主机「{name}」',

    'logmsg.err.addHost': '添加主机失败',
    'logmsg.err.saveRule': '保存规则失败',
    'logmsg.err.saveHost': '保存主机失败',
    'logmsg.err.deleteHost': '删除主机失败',
    'logmsg.err.addRule': '新增规则失败',
    'logmsg.err.removeRule': '删除规则失败',
    'logmsg.err.updateRule': '保存规则字段失败',
    'logmsg.err.connect': '连接失败',
    'logmsg.err.disconnect': '断开失败',
    'logmsg.err.pickKey': '选择私钥失败',
    'logmsg.err.loadHosts': '加载主机列表失败',

    'tray.show': '显示主窗口',
    'tray.closeToTray': '关闭时最小化到托盘',
    'tray.quit': '退出',

    'closeDlg.title': '关闭程序',
    'closeDlg.message': '当前有活动的 SSH 连接。是否将程序最小化到系统托盘以保持隧道运行？选择"最小化到托盘"将被记住，之后不再询问；选择"退出"不会保存偏好并直接退出，下次连接中关闭仍会询问。',
    'closeDlg.toTray': '最小化到托盘',
    'closeDlg.exit': '退出程序',

    'startDlg.title': '开启最小化到托盘？',
    'startDlg.message': '当前未开启"关闭时最小化到托盘"。开启后，点击关闭窗口时程序将收容到托盘，隧道保持运行。是否开启？',
    'startDlg.enable': '开启',

    'topbar.language': '语言',
    'topbar.theme': '主题',
    'topbar.settings': '设置',
    'topbar.connect': '连接',
    'topbar.forward': '端口转发',
    'topbar.logs': '运行日志',

    'sidebar.searchPlaceholder': '搜索主机',
    'sidebar.savedHosts': '已保存主机',
    'sidebar.addHost': '添加主机',
    'sidebar.collapse': '收起侧边栏',
    'sidebar.expand': '展开侧边栏',
    'sidebar.language': '语言',
    'sidebar.theme': '主题',
    'sidebar.settings': '设置',
    'sidebar.rename': '重命名',

    'auth.password': '密码',
    'auth.privateKey': '私钥',
    'auth.keyFile': '私钥文件',
    'auth.chooseFile': '选择文件',
    'auth.passphrase': '私钥密码',
    'auth.passphraseHint': '（可选，留空表示私钥未加密）',
    'auth.keyLoaded': '已加载 {type} 私钥 · {fingerprint}',
    'auth.nameRequired': '主机名称不能为空',

    'conn.overview': '隧道概览',
    'conn.rules': '转发规则',
    'conn.activeTunnels': '活跃隧道',
    'conn.totalTraffic': '累计流量',
    'conn.uptime': '运行时长',

    'dialog.addHostTitle': '新增主机',
    'dialog.addHostSubtitle': '填写连接信息后保存到侧边栏主机列表',
    'dialog.escClose': 'Esc 关闭',
    'dialog.escHint': '关闭',
    'dialog.groupConnect': '连接信息',
    'dialog.groupAuth': '认证信息',
    'dialog.nameHint': '用于列表展示，可留空',
    'dialog.namePlaceholder': '例如：生产环境 Web-01',
    'dialog.hostPlaceholder': 'IP 或域名',
    'dialog.usernamePlaceholder': '登录用户名',

    'auth.method': '认证方式',
    'auth.passwordPlaceholder': '请输入登录密码',

    'settings.title': '设置',
    'settings.theme': '主题',
    'settings.locale': '语言',
    'settings.minimizeToTray': '关闭时最小化到托盘',
    'settings.autoStart': '开机自启',
    'settings.dark': '深色',
    'settings.light': '浅色',
    'settings.zh': '简体中文',
    'settings.en': 'English',
    'settings.close': '关闭',
  },
  en: {
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.rename': 'Rename',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.local': 'Local',
    'common.remote': 'Remote',
    'common.dynamic': 'Dynamic',
    'common.note': 'Note',
    'common.actions': 'Actions',
    'common.enable': 'Enable',
    'common.listenAddr': 'Listen Address',
    'common.targetAddr': 'Target Address',
    'common.remoteAddr': 'Remote Address',
    'common.localAddr': 'Local Address',
    'common.unnamed': 'Untitled Host',
    'common.unknown': 'Unknown',

    'hostbar.title': 'Saved Hosts',
    'hostbar.namePlaceholder': 'Host name',
    'hostbar.addHost': 'Add Host',

    'lang.title': 'Language',
    'lang.zh': '简体中文',
    'lang.en': 'English',

    'theme.title': 'Theme',
    'theme.dark': 'Dark',
    'theme.light': 'Light',

    'conn.title': 'SSH Connection',
    'conn.subtitle': 'Fill in remote host credentials to establish the tunnel',
    'conn.host': 'Host',
    'conn.port': 'Port',
    'conn.username': 'Username',
    'conn.password': 'Password',
    'conn.keyPath': 'Private Key Path',
    'conn.keyPathPlaceholder': 'Optional, leave blank to use password auth',
    'conn.browse': 'Browse',
    'conn.start': 'Start',
    'conn.stop': 'Stop',
    'conn.connecting': 'Connecting…',
    'conn.show': 'Show',
    'conn.hide': 'Hide',

    'pf.title': 'Port Forward Rules',
    'pf.add': 'Add Rule',

    'rt.targetRemote': 'Remote → Local',
    'rt.arrow': 'Remote → Local',
    'rt.upload': 'Up',
    'rt.download': 'Down',
    'rt.empty.local': 'No local forward rules',
    'rt.empty.remote': 'No remote forward rules',
    'rt.empty.dynamic': 'No dynamic forward rules',
    'rt.edit': 'Edit',
    'rt.delete': 'Delete',

    'rm.title': 'Edit Forward Rule',
    'rm.type': 'Forward Type',
    'rm.notePlaceholder': 'Optional note',

    'log.title': 'Runtime Logs',
    'log.count': '{n} entries',
    'log.copy': 'Copy All',
    'log.copied': 'Copied',
    'log.clear': 'Clear',
    'log.empty': 'No logs',

    'status.idle': 'Idle',
    'status.connecting': 'Connecting',
    'status.connected': 'Connected',
    'status.error': 'Connection Failed',
    'status.disconnecting': 'Disconnecting',

    'logmsg.switchHost': 'Switched host: {name} ({host})',
    'logmsg.saveHost': 'Saved host "{name}" config',
    'logmsg.deleteHost': 'Deleted host "{name}"',
    'logmsg.addRule': 'Added rule {desc}',
    'logmsg.draft': 'draft',
    'logmsg.removeRule': 'Removed rule {desc}',
    'logmsg.toggleRule': 'Rule {desc}',
    'logmsg.enabled': 'enabled',
    'logmsg.disabled': 'disabled',
    'logmsg.updateRule': 'Rule updated {desc} ({field})',
    'logmsg.modifyRule': 'Rule modified {desc}',
    'logmsg.noHost': 'No host selected',
    'logmsg.hostRequired': 'Host address cannot be empty',
    'logmsg.portInvalid': 'Port must be 1-65535',
    'logmsg.usernameRequired': 'Username cannot be empty',
    'logmsg.validateFail': 'Validation failed, please check required fields',
    'logmsg.connecting': 'Connecting to {host}:{port} (user {username})…',
    'logmsg.connected': 'Connected to {host}:{port}',
    'logmsg.noEnabledRule': 'No enabled forward rules',
    'logmsg.established': 'Established forward {desc}',
    'logmsg.closing': 'Closing all forward channels…',
    'logmsg.disconnected': 'Disconnected from {host}',
    'logmsg.pickKey': 'Selected private key: {path}',
    'logmsg.loading': 'Loading host config…',
    'logmsg.loaded': 'Loaded {n} host configs',
    'logmsg.waiting': 'Waiting for connection…',
    'logmsg.createdDefaultHost': 'Created default host "{name}"',
    'logmsg.addHost': 'Added host "{name}"',
    'logmsg.saveHostFirst': 'Please save the host config first',
    'logmsg.discardHost': 'Discarded unsaved host "{name}"',

    'logmsg.err.addHost': 'Failed to add host',
    'logmsg.err.saveRule': 'Failed to save rule',
    'logmsg.err.saveHost': 'Failed to save host',
    'logmsg.err.deleteHost': 'Failed to delete host',
    'logmsg.err.addRule': 'Failed to add rule',
    'logmsg.err.removeRule': 'Failed to remove rule',
    'logmsg.err.updateRule': 'Failed to update rule field',
    'logmsg.err.connect': 'Connection failed',
    'logmsg.err.disconnect': 'Disconnect failed',
    'logmsg.err.pickKey': 'Failed to select private key',
    'logmsg.err.loadHosts': 'Failed to load hosts',

    'tray.show': 'Show Main Window',
    'tray.closeToTray': 'Minimize to Tray on Close',
    'tray.quit': 'Quit',

    'closeDlg.title': 'Close Application',
    'closeDlg.message': 'An SSH connection is active. Minimize to the system tray to keep the tunnel running? Choosing "Minimize to Tray" is remembered and you won\'t be asked again; choosing "Exit" exits now without saving, so you\'ll be asked again next time you close while connected.',
    'closeDlg.toTray': 'Minimize to Tray',
    'closeDlg.exit': 'Exit',

    'startDlg.title': 'Enable Minimize to Tray?',
    'startDlg.message': '"Minimize to Tray on Close" is not enabled yet. Once enabled, closing the window keeps the app in the tray and the tunnel running. Enable it now?',
    'startDlg.enable': 'Enable',

    'topbar.language': 'Language',
    'topbar.theme': 'Theme',
    'topbar.settings': 'Settings',
    'topbar.connect': 'Connect',
    'topbar.forward': 'Forwarding',
    'topbar.logs': 'Logs',

    'sidebar.searchPlaceholder': 'Search hosts',
    'sidebar.savedHosts': 'Saved Hosts',
    'sidebar.addHost': 'Add Host',
    'sidebar.collapse': 'Collapse sidebar',
    'sidebar.expand': 'Expand sidebar',
    'sidebar.language': 'Language',
    'sidebar.theme': 'Theme',
    'sidebar.settings': 'Settings',
    'sidebar.rename': 'Rename',

    'auth.password': 'Password',
    'auth.privateKey': 'Private Key',
    'auth.keyFile': 'Private Key File',
    'auth.chooseFile': 'Choose File',
    'auth.passphrase': 'Key Passphrase',
    'auth.passphraseHint': '(optional, leave blank if the key is not encrypted)',
    'auth.keyLoaded': 'Loaded {type} private key · {fingerprint}',
    'auth.nameRequired': 'Host name cannot be empty',

    'conn.overview': 'Tunnel Overview',
    'conn.rules': 'Forward Rules',
    'conn.activeTunnels': 'Active Tunnels',
    'conn.totalTraffic': 'Total Traffic',
    'conn.uptime': 'Uptime',

    'dialog.addHostTitle': 'Add Host',
    'dialog.addHostSubtitle': 'Fill in connection info to save to the sidebar host list',
    'dialog.escClose': 'Esc to close',
    'dialog.escHint': 'to close',
    'dialog.groupConnect': 'Connection',
    'dialog.groupAuth': 'Authentication',
    'dialog.nameHint': 'Shown in the list, optional',
    'dialog.namePlaceholder': 'e.g. Production Web-01',
    'dialog.hostPlaceholder': 'IP or domain',
    'dialog.usernamePlaceholder': 'Login username',

    'auth.method': 'Auth Method',
    'auth.passwordPlaceholder': 'Enter login password',

    'settings.title': 'Settings',
    'settings.theme': 'Theme',
    'settings.locale': 'Language',
    'settings.minimizeToTray': 'Minimize to Tray on Close',
    'settings.autoStart': 'Launch at Startup',
    'settings.dark': 'Dark',
    'settings.light': 'Light',
    'settings.zh': '简体中文',
    'settings.en': 'English',
    'settings.close': 'Close',
  },
};

/** 翻译函数，支持 {name} 插值。读取 useSettings 的响应式 locale，语言切换即重渲染 */
export function t(key: string, params?: Record<string, string | number>): string {
  const template = messages[settings.locale]?.[key] ?? messages.zh[key] ?? key;
  if (!params) return template;
  return template.replace(/\{(\w+)\}/g, (_m, name: string) =>
    params[name] !== undefined ? String(params[name]) : '',
  );
}

